//! Per-node config editors and the single-node kind picker.
//!
//! One editor function per [`NodeKind`] inner config, generated by the
//! `impl_node_editor!` declarative macro (a trimmed cousin of texture's
//! `impl_config_editor!`).  Every editor has the shape:
//!
//! ```text
//! pub fn xxx_editor(ui: &mut egui::Ui, cfg: &mut XxxConfig) -> EditorResponse
//! ```
//!
//! and renders only its fields — *no* surrounding collapsing header — so the
//! same function works inside a canvas node box, an inspector panel, or a
//! plain window.  [`node_kind_editor`] wraps a kind picker around the right
//! body for editing a whole [`NodeKind`] in one call.
//!
//! Slider ranges are lifted from each config's `impl_genotype!` invocation so
//! the editor bounds match the evolutionary search bounds (frequencies and
//! rates use logarithmic sliders to match their `f32_log` mutation kind).

use bevy_egui::egui;

use crate::adsr::{AdsrCurve, AdsrEnvelope};
use crate::chorus::Chorus;
use crate::filter::{BiquadBandpass, BiquadHighpass, BiquadLowpass};
use crate::gate::Gate;
use crate::lfo::{Lfo, LfoShape};
use crate::mix::{Gain, Mix};
use crate::node::NodeKind;
use crate::noise::{BrownNoise, PinkNoise, WhiteNoise};
use crate::oscillator::{SawPolarity, SawtoothOsc, SineOsc, SquareOsc, TriangleOsc};
use crate::reverb::Reverb;

use super::{EditorResponse, bool_instant, drag_debounced, slider_debounced};

// ---------------------------------------------------------------------------
// Editor-generating macro
// ---------------------------------------------------------------------------

/// Generate a per-node editor function from a concise field description.
///
/// Widget kinds:
///
/// | Kind | Widget |
/// |------|--------|
/// | `slider(label, field, range)` | linear `f32` slider |
/// | `slider_log(label, field, range)` | logarithmic `f32` slider (freq/rate) |
/// | `drag(label, field, speed, range)` | `f32` drag value, clamped to range |
/// | `bool(label, field)` | checkbox |
/// | `enum_select(label, field, [(Btn, Variant), …])` | selectable-row picker |
macro_rules! impl_node_editor {
    (
        $(#[doc = $doc:expr])*
        fn $fn_name:ident, $Config:ty =>
        { $( $w:ident $args:tt ),* $(,)? }
    ) => {
        $(#[doc = $doc])*
        pub fn $fn_name(ui: &mut egui::Ui, cfg: &mut $Config) -> EditorResponse {
            #[allow(unused_mut)]
            let mut res = EditorResponse::NONE;
            $( impl_node_editor!(@w ui, cfg, res, $w $args); )*
            res
        }
    };

    // f32 linear slider.
    (@w $ui:ident, $cfg:ident, $res:ident, slider ($label:expr, $field:ident, $range:expr)) => {
        $res.merge(slider_debounced(
            $ui,
            egui::Slider::new(&mut $cfg.$field, $range).text($label),
        ));
    };
    // f32 logarithmic slider — for frequencies / rates (matches `f32_log`).
    (@w $ui:ident, $cfg:ident, $res:ident, slider_log ($label:expr, $field:ident, $range:expr)) => {
        $res.merge(slider_debounced(
            $ui,
            egui::Slider::new(&mut $cfg.$field, $range)
                .logarithmic(true)
                .text($label),
        ));
    };
    // f32 drag value (wide-range amounts), clamped to `range`.
    (@w $ui:ident, $cfg:ident, $res:ident, drag ($label:expr, $field:ident, $speed:expr, $range:expr)) => {
        $res.merge(drag_debounced($ui, $label, &mut $cfg.$field, $speed, $range));
    };
    // bool checkbox.
    (@w $ui:ident, $cfg:ident, $res:ident, bool ($label:expr, $field:ident)) => {
        $res.merge(bool_instant($ui, &mut $cfg.$field, $label));
    };
    // enum selectable-row picker.  Variants must be `Copy + PartialEq`.
    (@w $ui:ident, $cfg:ident, $res:ident,
     enum_select ($label:expr, $field:ident, [ $(($btn:expr, $variant:expr)),+ $(,)? ])) => {
        $ui.horizontal(|ui| {
            ui.label($label);
            $(
                let selected = $cfg.$field == $variant;
                if ui.selectable_label(selected, $btn).clicked() && !selected {
                    $cfg.$field = $variant;
                    $res.changed = true;
                    $res.rebake = true;
                }
            )+
        });
    };
}

// ---------------------------------------------------------------------------
// Per-node editors — one invocation per NodeKind inner config
// ---------------------------------------------------------------------------

impl_node_editor!(
    /// Editor for a [`SineOsc`] — pure-tone sine oscillator.
    fn sine_osc_editor, SineOsc => {
        slider_log("Freq (Hz)", freq_hz, 20.0..=20_000.0),
        slider("Phase", phase_offset, 0.0..=1.0),
        slider("Amplitude", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for a [`SquareOsc`] — pulse-width square oscillator.
    fn square_osc_editor, SquareOsc => {
        slider_log("Freq (Hz)", freq_hz, 20.0..=20_000.0),
        slider("Duty", duty, 0.05..=0.95),
        slider("Amplitude", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for a [`SawtoothOsc`] — sawtooth with selectable polarity.
    fn sawtooth_osc_editor, SawtoothOsc => {
        slider_log("Freq (Hz)", freq_hz, 20.0..=20_000.0),
        enum_select("Polarity", polarity, [
            ("Up", SawPolarity::Up),
            ("Down", SawPolarity::Down),
        ]),
        slider("Amplitude", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for a [`TriangleOsc`] — symmetric triangle oscillator.
    fn triangle_osc_editor, TriangleOsc => {
        slider_log("Freq (Hz)", freq_hz, 20.0..=20_000.0),
        slider("Amplitude", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for [`WhiteNoise`].
    fn white_noise_editor, WhiteNoise => {
        slider("Amplitude", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for [`PinkNoise`].
    fn pink_noise_editor, PinkNoise => {
        slider("Amplitude", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for [`BrownNoise`].
    fn brown_noise_editor, BrownNoise => {
        slider("Amplitude", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for an [`AdsrEnvelope`].  Times use logarithmic sliders (they
    /// mutate multiplicatively); sustain is a linear `[0, 1]` level.
    fn adsr_envelope_editor, AdsrEnvelope => {
        slider_log("Attack (s)", attack_s, 0.001..=10.0),
        slider_log("Decay (s)", decay_s, 0.001..=10.0),
        slider("Sustain", sustain_level, 0.0..=1.0),
        slider_log("Release (s)", release_s, 0.001..=10.0),
        enum_select("Curve", curve, [
            ("Linear", AdsrCurve::Linear),
            ("Exp", AdsrCurve::Exponential),
        ]),
    }
);

impl_node_editor!(
    /// Editor for a [`BiquadLowpass`] filter.
    fn biquad_lowpass_editor, BiquadLowpass => {
        slider_log("Cutoff (Hz)", cutoff_hz, 20.0..=20_000.0),
        slider("Q", q, 0.1..=20.0),
    }
);

impl_node_editor!(
    /// Editor for a [`BiquadHighpass`] filter.
    fn biquad_highpass_editor, BiquadHighpass => {
        slider_log("Cutoff (Hz)", cutoff_hz, 20.0..=20_000.0),
        slider("Q", q, 0.1..=20.0),
    }
);

impl_node_editor!(
    /// Editor for a [`BiquadBandpass`] filter (constant-peak-gain variant).
    fn biquad_bandpass_editor, BiquadBandpass => {
        slider_log("Center (Hz)", center_hz, 20.0..=20_000.0),
        slider("Q", q, 0.1..=20.0),
    }
);

impl_node_editor!(
    /// Editor for an [`Lfo`].  Depth/offset are wide-range drag values
    /// (an LFO routed to a filter cutoff sweeps thousands of Hz).
    fn lfo_editor, Lfo => {
        slider_log("Rate (Hz)", rate_hz, 0.01..=30.0),
        enum_select("Shape", shape, [
            ("Sine", LfoShape::Sine),
            ("Tri", LfoShape::Triangle),
            ("Sqr", LfoShape::Square),
            ("Saw", LfoShape::Saw),
            ("Rnd", LfoShape::Random),
        ]),
        drag("Depth", depth, 1.0, 0.0..=10_000.0),
        drag("Offset", offset, 1.0, (-10_000.0)..=10_000.0),
    }
);

impl_node_editor!(
    /// Editor for a [`Mix`] node (additive bus with a master gain).
    fn mix_editor, Mix => {
        slider("Gain", gain, 0.0..=4.0),
    }
);

impl_node_editor!(
    /// Editor for a [`Gain`] node (voltage-controlled amplifier).
    fn gain_editor, Gain => {
        slider("Gain", gain, 0.0..=4.0),
    }
);

impl_node_editor!(
    /// Editor for a [`Gate`] node.
    fn gate_editor, Gate => {
        bool("Invert", invert),
    }
);

impl_node_editor!(
    /// Editor for a [`Chorus`] effect.  Rate uses a logarithmic slider (it
    /// mutates multiplicatively); the rest are linear.
    fn chorus_editor, Chorus => {
        slider_log("Rate (Hz)", rate_hz, 0.05..=12.0),
        slider("Depth (ms)", depth_ms, 0.0..=20.0),
        slider("Base delay (ms)", base_delay_ms, 1.0..=40.0),
        slider("Feedback", feedback, 0.0..=0.95),
        slider("Mix", mix, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for a [`Reverb`] effect (mono Freeverb).
    fn reverb_editor, Reverb => {
        slider("Room size", room_size, 0.0..=1.0),
        slider("Damping", damping, 0.0..=1.0),
        slider("Mix", mix, 0.0..=1.0),
    }
);

// ---------------------------------------------------------------------------
// NodeKind-level editor (kind picker + body)
// ---------------------------------------------------------------------------

/// Node kinds in display order for the picker dropdown.
const KIND_LABELS: [&str; 18] = [
    "Silence",
    "Sine",
    "Square",
    "Sawtooth",
    "Triangle",
    "White Noise",
    "Pink Noise",
    "Brown Noise",
    "ADSR",
    "Lowpass",
    "Highpass",
    "Bandpass",
    "LFO",
    "Mix",
    "Gain",
    "Gate",
    "Chorus",
    "Reverb",
];

/// Human-readable label for a node kind — used by the kind picker and (in
/// later phases) by canvas node-box headers.
pub fn node_kind_label(kind: &NodeKind) -> &'static str {
    match kind {
        NodeKind::Silence => "Silence",
        NodeKind::Sine(_) => "Sine",
        NodeKind::Square(_) => "Square",
        NodeKind::Sawtooth(_) => "Sawtooth",
        NodeKind::Triangle(_) => "Triangle",
        NodeKind::WhiteNoise(_) => "White Noise",
        NodeKind::PinkNoise(_) => "Pink Noise",
        NodeKind::BrownNoise(_) => "Brown Noise",
        NodeKind::Adsr(_) => "ADSR",
        NodeKind::BiquadLowpass(_) => "Lowpass",
        NodeKind::BiquadHighpass(_) => "Highpass",
        NodeKind::BiquadBandpass(_) => "Bandpass",
        NodeKind::Lfo(_) => "LFO",
        NodeKind::Mix(_) => "Mix",
        NodeKind::Gain(_) => "Gain",
        NodeKind::Gate(_) => "Gate",
        NodeKind::Chorus(_) => "Chorus",
        NodeKind::Reverb(_) => "Reverb",
    }
}

/// Build a default node of the kind named by `label` (the inverse of
/// [`node_kind_label`]).  Unknown labels fall back to [`NodeKind::Silence`].
fn default_kind_for(label: &str) -> NodeKind {
    match label {
        "Sine" => NodeKind::Sine(SineOsc::default()),
        "Square" => NodeKind::Square(SquareOsc::default()),
        "Sawtooth" => NodeKind::Sawtooth(SawtoothOsc::default()),
        "Triangle" => NodeKind::Triangle(TriangleOsc::default()),
        "White Noise" => NodeKind::WhiteNoise(WhiteNoise::default()),
        "Pink Noise" => NodeKind::PinkNoise(PinkNoise::default()),
        "Brown Noise" => NodeKind::BrownNoise(BrownNoise::default()),
        "ADSR" => NodeKind::Adsr(AdsrEnvelope::default()),
        "Lowpass" => NodeKind::BiquadLowpass(BiquadLowpass::default()),
        "Highpass" => NodeKind::BiquadHighpass(BiquadHighpass::default()),
        "Bandpass" => NodeKind::BiquadBandpass(BiquadBandpass::default()),
        "LFO" => NodeKind::Lfo(Lfo::default()),
        "Mix" => NodeKind::Mix(Mix::default()),
        "Gain" => NodeKind::Gain(Gain::default()),
        "Gate" => NodeKind::Gate(Gate::default()),
        "Chorus" => NodeKind::Chorus(Chorus::default()),
        "Reverb" => NodeKind::Reverb(Reverb::default()),
        _ => NodeKind::Silence,
    }
}

/// Render only the parameter widgets for `kind` — no kind picker, no header.
///
/// Use this when the surrounding UI already conveys the node's type (e.g. a
/// canvas node box that paints the kind name in its title bar).
pub fn node_kind_body(ui: &mut egui::Ui, kind: &mut NodeKind) -> EditorResponse {
    match kind {
        NodeKind::Silence => {
            ui.label("No parameters.");
            EditorResponse::NONE
        }
        NodeKind::Sine(o) => sine_osc_editor(ui, o),
        NodeKind::Square(o) => square_osc_editor(ui, o),
        NodeKind::Sawtooth(o) => sawtooth_osc_editor(ui, o),
        NodeKind::Triangle(o) => triangle_osc_editor(ui, o),
        NodeKind::WhiteNoise(n) => white_noise_editor(ui, n),
        NodeKind::PinkNoise(n) => pink_noise_editor(ui, n),
        NodeKind::BrownNoise(n) => brown_noise_editor(ui, n),
        NodeKind::Adsr(e) => adsr_envelope_editor(ui, e),
        NodeKind::BiquadLowpass(f) => biquad_lowpass_editor(ui, f),
        NodeKind::BiquadHighpass(f) => biquad_highpass_editor(ui, f),
        NodeKind::BiquadBandpass(f) => biquad_bandpass_editor(ui, f),
        NodeKind::Lfo(l) => lfo_editor(ui, l),
        NodeKind::Mix(m) => mix_editor(ui, m),
        NodeKind::Gain(g) => gain_editor(ui, g),
        NodeKind::Gate(g) => gate_editor(ui, g),
        NodeKind::Chorus(c) => chorus_editor(ui, c),
        NodeKind::Reverb(r) => reverb_editor(ui, r),
    }
}

/// Full editor for one [`NodeKind`]: a kind-picker combo box plus the selected
/// variant's parameter widgets.
///
/// `id` scopes egui widget ids so multiple node editors can live in one `Ui`
/// (e.g. an inspector list, or the Phase-2 graph canvas) without colliding.
/// Picking a new kind from the dropdown replaces the node with that kind's
/// `Default`, which counts as both a change and a commit.
pub fn node_kind_editor(ui: &mut egui::Ui, kind: &mut NodeKind, id: egui::Id) -> EditorResponse {
    let mut res = EditorResponse::NONE;
    ui.push_id(id, |ui| {
        egui::ComboBox::from_label("Kind")
            .selected_text(node_kind_label(kind))
            .show_ui(ui, |ui| {
                for label in KIND_LABELS {
                    let selected = node_kind_label(kind) == label;
                    if ui.selectable_label(selected, label).clicked() && !selected {
                        *kind = default_kind_for(label);
                        res.changed = true;
                        res.rebake = true;
                    }
                }
            });
        res.merge(node_kind_body(ui, kind));
    });
    res
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn label_round_trips_through_default_kind() {
        // Every label maps to a kind whose label is itself — so the picker's
        // selected-text and the dropdown rows stay consistent.
        for label in KIND_LABELS {
            let kind = default_kind_for(label);
            assert_eq!(
                node_kind_label(&kind),
                label,
                "round-trip failed for {label}"
            );
        }
    }

    #[test]
    fn unknown_label_falls_back_to_silence() {
        assert!(matches!(default_kind_for("nonsense"), NodeKind::Silence));
    }

    #[test]
    fn every_kind_label_is_listed_in_the_picker() {
        // Guards against adding a NodeKind variant but forgetting the picker
        // entry: each variant's label must appear in KIND_LABELS.
        let all = [
            NodeKind::Silence,
            NodeKind::Sine(SineOsc::default()),
            NodeKind::Square(SquareOsc::default()),
            NodeKind::Sawtooth(SawtoothOsc::default()),
            NodeKind::Triangle(TriangleOsc::default()),
            NodeKind::WhiteNoise(WhiteNoise::default()),
            NodeKind::PinkNoise(PinkNoise::default()),
            NodeKind::BrownNoise(BrownNoise::default()),
            NodeKind::Adsr(AdsrEnvelope::default()),
            NodeKind::BiquadLowpass(BiquadLowpass::default()),
            NodeKind::BiquadHighpass(BiquadHighpass::default()),
            NodeKind::BiquadBandpass(BiquadBandpass::default()),
            NodeKind::Lfo(Lfo::default()),
            NodeKind::Mix(Mix::default()),
            NodeKind::Gain(Gain::default()),
            NodeKind::Gate(Gate::default()),
            NodeKind::Chorus(Chorus::default()),
            NodeKind::Reverb(Reverb::default()),
        ];
        for kind in &all {
            assert!(
                KIND_LABELS.contains(&node_kind_label(kind)),
                "{} missing from KIND_LABELS",
                node_kind_label(kind)
            );
        }
    }
}
