//! Per-node config editors and the single-node kind picker.
//!
//! One editor function per [`NodeKind`] inner config, generated by the
//! `impl_node_editor!` declarative macro (a trimmed cousin of texture's
//! `impl_config_editor!`).  Every editor has the shape:
//!
//! ```text
//! pub fn xxx_editor(ui: &mut egui::Ui, cfg: &mut XxxConfig) -> EditorResponse
//! ```
//!
//! and renders only its fields — *no* surrounding collapsing header — so the
//! same function works inside a canvas node box, an inspector panel, or a
//! plain window.  [`node_kind_editor`] wraps a kind picker around the right
//! body for editing a whole [`NodeKind`] in one call.
//!
//! Slider ranges are lifted from each config's `impl_genotype!` invocation so
//! the editor bounds match the evolutionary search bounds (frequencies and
//! rates use logarithmic sliders to match their `f32_log` mutation kind).

use bevy_egui::egui;

use crate::adsr::{AdsrCurve, AdsrEnvelope};
use crate::chorus::Chorus;
use crate::filter::{BiquadBandpass, BiquadHighpass, BiquadLowpass};
use crate::gate::Gate;
use crate::lfo::{Lfo, LfoShape};
use crate::mix::{Gain, Mix};
use crate::node::NodeKind;
use crate::noise::{BrownNoise, PinkNoise, WhiteNoise};
use crate::oscillator::{AntiAlias, SawPolarity, SawtoothOsc, SineOsc, SquareOsc, TriangleOsc};
use crate::reverb::Reverb;

use super::{EditorResponse, bool_instant, drag_value_debounced, slider_debounced};

// ---------------------------------------------------------------------------
// Editor-generating macro
// ---------------------------------------------------------------------------

/// One config's parameter widgets, reachable from the config *type*.
///
/// Every node config implements this, generated alongside its `*_editor`
/// function by `impl_node_editor!` below. It exists so `node_kind_body` can
/// be generated from `symbios_audio::for_each_node_kind!`: the roster names
/// each variant's config type, not the name of the function that edits it,
/// so a type-dispatched call is the only handle it can offer. Private —
/// callers use the `*_editor` functions or `node_kind_body`.
trait NodeConfigEditor {
    fn edit(&mut self, ui: &mut egui::Ui) -> EditorResponse;
}

/// Generate a per-node editor function from a concise field description.
///
/// The fields become the rows of a two-column grid — the name on the left,
/// the control on the right, the unit written into the value ("500 Hz",
/// "0.40 s") — so every name in a node box starts at the same edge (#59,
/// Overlands #1332). `Slider::text` used to put the name *after* the value,
/// which set each name's position by how wide its value happened to be and
/// ran the long ones up against the box's border.
///
/// Widget kinds:
///
/// | Kind | Widget |
/// |------|--------|
/// | `slider(label, unit, field, range)` | linear `f32` slider |
/// | `slider_log(label, unit, field, range)` | logarithmic `f32` slider (freq/rate) |
/// | `drag(label, unit, field, speed, range)` | `f32` drag value, clamped to range |
/// | `bool(label, field)` | checkbox |
/// | `enum_select(label, field, [(Btn, Variant), …])` | selectable-row picker |
///
/// A trailing `note "…"` writes one weak line under the grid — for what a
/// node does that its parameters do not show (a [`Gate`]'s window).
macro_rules! impl_node_editor {
    (
        $(#[doc = $doc:expr])*
        fn $fn_name:ident, $Config:ty =>
        { $( $w:ident $args:tt ),* $(,)? }
        $( note $note:expr )?
    ) => {
        $(#[doc = $doc])*
        pub fn $fn_name(ui: &mut egui::Ui, cfg: &mut $Config) -> EditorResponse {
            #[allow(unused_mut)]
            let mut res = EditorResponse::NONE;
            egui::Grid::new(concat!(stringify!($fn_name), "_rows"))
                .num_columns(2)
                .show(ui, |ui| {
                    $( impl_node_editor!(@w ui, cfg, res, $w $args); )*
                });
            $( ui.label(egui::RichText::new($note).weak()); )?
            res
        }

        impl NodeConfigEditor for $Config {
            fn edit(&mut self, ui: &mut egui::Ui) -> EditorResponse {
                $fn_name(ui, self)
            }
        }
    };

    // f32 linear slider.
    (@w $ui:ident, $cfg:ident, $res:ident,
     slider ($label:expr, $unit:expr, $field:ident, $range:expr)) => {
        $ui.label($label);
        $res.merge(slider_debounced(
            $ui,
            egui::Slider::new(&mut $cfg.$field, $range).suffix($unit),
        ));
        $ui.end_row();
    };
    // f32 logarithmic slider — for frequencies / rates (matches `f32_log`).
    (@w $ui:ident, $cfg:ident, $res:ident,
     slider_log ($label:expr, $unit:expr, $field:ident, $range:expr)) => {
        $ui.label($label);
        $res.merge(slider_debounced(
            $ui,
            egui::Slider::new(&mut $cfg.$field, $range)
                .logarithmic(true)
                .suffix($unit),
        ));
        $ui.end_row();
    };
    // f32 drag value (wide-range amounts), clamped to `range`.
    (@w $ui:ident, $cfg:ident, $res:ident,
     drag ($label:expr, $unit:expr, $field:ident, $speed:expr, $range:expr)) => {
        $ui.label($label);
        $res.merge(drag_value_debounced(
            $ui,
            &mut $cfg.$field,
            $speed,
            $range,
            $unit,
        ));
        $ui.end_row();
    };
    // bool checkbox — the name is the grid's left cell, so the box itself
    // carries no label of its own.
    (@w $ui:ident, $cfg:ident, $res:ident, bool ($label:expr, $field:ident)) => {
        $ui.label($label);
        $res.merge(bool_instant($ui, &mut $cfg.$field, ""));
        $ui.end_row();
    };
    // enum selectable-row picker.  Variants must be `Copy + PartialEq`.
    (@w $ui:ident, $cfg:ident, $res:ident,
     enum_select ($label:expr, $field:ident, [ $(($btn:expr, $variant:expr)),+ $(,)? ])) => {
        $ui.label($label);
        $ui.horizontal(|ui| {
            $(
                let selected = $cfg.$field == $variant;
                if ui.selectable_label(selected, $btn).clicked() && !selected {
                    $cfg.$field = $variant;
                    $res.changed = true;
                    $res.rebake = true;
                }
            )+
        });
        $ui.end_row();
    };
}

// ---------------------------------------------------------------------------
// Per-node editors — one invocation per NodeKind inner config
// ---------------------------------------------------------------------------

impl_node_editor!(
    /// Editor for a [`SineOsc`] — pure-tone sine oscillator.
    fn sine_osc_editor, SineOsc => {
        slider_log("Frequency", " Hz", freq_hz, 20.0..=20_000.0),
        slider("Phase", "", phase_offset, 0.0..=1.0),
        slider("Amplitude", "", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for a [`SquareOsc`] — pulse-width square oscillator.
    fn square_osc_editor, SquareOsc => {
        slider_log("Frequency", " Hz", freq_hz, 20.0..=20_000.0),
        slider("Duty", "", duty, 0.05..=0.95),
        slider("Amplitude", "", amplitude, 0.0..=1.0),
        enum_select("Anti-alias", anti_alias, [
            ("Naive", AntiAlias::Naive),
            ("BLEP", AntiAlias::PolyBlep),
        ]),
    }
);

impl_node_editor!(
    /// Editor for a [`SawtoothOsc`] — sawtooth with selectable polarity.
    fn sawtooth_osc_editor, SawtoothOsc => {
        slider_log("Frequency", " Hz", freq_hz, 20.0..=20_000.0),
        enum_select("Polarity", polarity, [
            ("Up", SawPolarity::Up),
            ("Down", SawPolarity::Down),
        ]),
        slider("Amplitude", "", amplitude, 0.0..=1.0),
        enum_select("Anti-alias", anti_alias, [
            ("Naive", AntiAlias::Naive),
            ("BLEP", AntiAlias::PolyBlep),
        ]),
    }
);

impl_node_editor!(
    /// Editor for a [`TriangleOsc`] — symmetric triangle oscillator.
    fn triangle_osc_editor, TriangleOsc => {
        slider_log("Frequency", " Hz", freq_hz, 20.0..=20_000.0),
        slider("Amplitude", "", amplitude, 0.0..=1.0),
        enum_select("Anti-alias", anti_alias, [
            ("Naive", AntiAlias::Naive),
            ("BLEP", AntiAlias::PolyBlep),
        ]),
    }
);

impl_node_editor!(
    /// Editor for [`WhiteNoise`].
    fn white_noise_editor, WhiteNoise => {
        slider("Amplitude", "", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for [`PinkNoise`].
    fn pink_noise_editor, PinkNoise => {
        slider("Amplitude", "", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for [`BrownNoise`].
    fn brown_noise_editor, BrownNoise => {
        slider("Amplitude", "", amplitude, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for an [`AdsrEnvelope`].  Times use logarithmic sliders (they
    /// mutate multiplicatively); sustain is a linear `[0, 1]` level.
    fn adsr_envelope_editor, AdsrEnvelope => {
        slider_log("Attack", " s", attack_s, 0.001..=10.0),
        slider_log("Decay", " s", decay_s, 0.001..=10.0),
        slider("Sustain", "", sustain_level, 0.0..=1.0),
        slider_log("Release", " s", release_s, 0.001..=10.0),
        enum_select("Curve", curve, [
            ("Linear", AdsrCurve::Linear),
            ("Exp", AdsrCurve::Exponential),
        ]),
    }
    note "The gate is always open in a standalone patch, so the envelope \
          holds at sustain and its release is never heard; a sequence's \
          notes open and close it."
);

impl_node_editor!(
    /// Editor for a [`BiquadLowpass`] filter.
    fn biquad_lowpass_editor, BiquadLowpass => {
        slider_log("Cutoff", " Hz", cutoff_hz, 20.0..=20_000.0),
        slider("Q", "", q, 0.1..=20.0),
    }
);

impl_node_editor!(
    /// Editor for a [`BiquadHighpass`] filter.
    fn biquad_highpass_editor, BiquadHighpass => {
        slider_log("Cutoff", " Hz", cutoff_hz, 20.0..=20_000.0),
        slider("Q", "", q, 0.1..=20.0),
    }
);

impl_node_editor!(
    /// Editor for a [`BiquadBandpass`] filter (constant-peak-gain variant).
    fn biquad_bandpass_editor, BiquadBandpass => {
        slider_log("Center", " Hz", center_hz, 20.0..=20_000.0),
        slider("Q", "", q, 0.1..=20.0),
    }
);

impl_node_editor!(
    /// Editor for an [`Lfo`].  Depth/offset are wide-range drag values
    /// (an LFO routed to a filter cutoff sweeps thousands of Hz).
    fn lfo_editor, Lfo => {
        slider_log("Rate", " Hz", rate_hz, 0.01..=30.0),
        enum_select("Shape", shape, [
            ("Sine", LfoShape::Sine),
            ("Tri", LfoShape::Triangle),
            ("Sqr", LfoShape::Square),
            ("Saw", LfoShape::Saw),
            ("Rnd", LfoShape::Random),
        ]),
        drag("Depth", "", depth, 1.0, 0.0..=10_000.0),
        drag("Offset", "", offset, 1.0, (-10_000.0)..=10_000.0),
    }
);

impl_node_editor!(
    /// Editor for a [`Mix`] node (additive bus with a master gain).
    fn mix_editor, Mix => {
        slider("Gain", "", gain, 0.0..=4.0),
    }
);

impl_node_editor!(
    /// Editor for a [`Gain`] node (voltage-controlled amplifier).
    fn gain_editor, Gain => {
        slider("Gain", "", gain, 0.0..=4.0),
    }
);

impl_node_editor!(
    /// Editor for a [`Gate`] node.
    fn gate_editor, Gate => {
        bool("Invert", invert),
    }
    note "The gate is always open in a standalone patch, so this holds at \
          1.0 throughout; a sequence's notes open and close it."
);

impl_node_editor!(
    /// Editor for a [`Chorus`] effect.  Rate uses a logarithmic slider (it
    /// mutates multiplicatively); the rest are linear.
    fn chorus_editor, Chorus => {
        slider_log("Rate", " Hz", rate_hz, 0.05..=12.0),
        slider("Depth", " ms", depth_ms, 0.0..=20.0),
        slider("Base delay", " ms", base_delay_ms, 1.0..=40.0),
        slider("Feedback", "", feedback, 0.0..=0.95),
        slider("Mix", "", mix, 0.0..=1.0),
    }
);

impl_node_editor!(
    /// Editor for a [`Reverb`] effect (mono Freeverb).
    fn reverb_editor, Reverb => {
        slider("Room size", "", room_size, 0.0..=1.0),
        slider("Damping", "", damping, 0.0..=1.0),
        slider("Mix", "", mix, 0.0..=1.0),
    }
);

// ---------------------------------------------------------------------------
// NodeKind-level editor (kind picker + body)
// ---------------------------------------------------------------------------

/// The picker, the labels and the per-kind body, all generated from
/// `symbios_audio::for_each_node_kind!`.
///
/// These three used to be hand-written lists, and the roster they encoded was
/// the *fourth* copy of the node vocabulary in the family — after
/// `symbios-audio`'s own enum and Overlands' two mirror rosters. `NodeKind` is
/// `#[non_exhaustive]`, so nothing here could ever be checked against it: a
/// kind added upstream simply never appeared in the dropdown, and the tests
/// below passed because they compared these lists against each other.
/// Generating them means a kind added upstream arrives in the picker, with a
/// default and an editor body, on the version bump alone.
macro_rules! define_kind_picker {
    (
        unit: { $(($uv:ident, $ul:literal)),* $(,)? }
        data: { $(($dv:ident, $dt:ty, $dl:literal)),* $(,)? }
    ) => {
        /// Node kinds in display order for the picker dropdown — upstream's
        /// roster order.
        const KIND_LABELS: &[&str] = &[ $( $ul, )* $( $dl, )* ];

        /// Build a default node of the kind named by `label` (the inverse of
        /// [`node_kind_label`]).  Unknown labels fall back to
        /// [`NodeKind::Silence`].
        fn default_kind_for(label: &str) -> NodeKind {
            match label {
                $( $ul => NodeKind::$uv, )*
                $( $dl => NodeKind::$dv(<$dt>::default()), )*
                _ => NodeKind::Silence,
            }
        }

        /// Render only the parameter widgets for `kind` — no kind picker, no
        /// header.
        ///
        /// Use this when the surrounding UI already conveys the node's type
        /// (e.g. a canvas node box that paints the kind name in its title
        /// bar).
        pub fn node_kind_body(ui: &mut egui::Ui, kind: &mut NodeKind) -> EditorResponse {
            match kind {
                $(
                    NodeKind::$uv => {
                        ui.label("No parameters.");
                        EditorResponse::NONE
                    }
                )*
                // Dispatched by config type through the private
                // `NodeConfigEditor` trait, which `impl_node_editor!`
                // implements for each config — the roster names types, not
                // function names.
                $( NodeKind::$dv(config) => config.edit(ui), )*
                // A patch written by a newer version of `symbios-audio`
                // decodes its unrecognised nodes here. There is nothing to
                // edit and nothing this build could safely write back
                // (`NodeKind::Unknown` is `skip_serializing` upstream), so
                // say so rather than showing an empty panel.
                NodeKind::Unknown => {
                    ui.label("This node was made by a newer version. It cannot be edited here, and saving this patch will be refused rather than overwrite it.");
                    EditorResponse::NONE
                }
                // `NodeKind` is `#[non_exhaustive]`, so the compiler keeps
                // this arm however complete the roster is.
                _ => {
                    ui.label("No editor for this node kind.");
                    EditorResponse::NONE
                }
            }
        }
    };
}

symbios_audio::for_each_node_kind!(define_kind_picker);

/// Human-readable label for a node kind — used by the kind picker and by
/// canvas node-box headers.
///
/// Delegates to `symbios-audio`'s own `NodeKind::label`, which is generated
/// from the same roster the picker is, so there is exactly one table of node
/// names in the family rather than one per crate.
pub fn node_kind_label(kind: &NodeKind) -> &'static str {
    kind.label()
}

/// The kind picker alone: a combo whose selected text is the kind's name,
/// with no caption of its own.
///
/// This is a node box's title on the canvas — the name *is* the title, and
/// changing the kind is done where the name is written (#59, Overlands
/// #1332 B5). The box used to carry both a title reading "#0 Sawtooth" and
/// a captioned "Kind" combo under it reading "Sawtooth" again, which spent
/// a third of the box's height saying one word twice.
///
/// `id` scopes the combo's widget ids, as for [`node_kind_editor`].
pub fn node_kind_picker(ui: &mut egui::Ui, kind: &mut NodeKind, id: egui::Id) -> EditorResponse {
    let mut res = EditorResponse::NONE;
    egui::ComboBox::from_id_salt(id)
        .selected_text(node_kind_label(kind))
        .show_ui(ui, |ui| {
            for label in KIND_LABELS.iter().copied() {
                let selected = node_kind_label(kind) == label;
                if ui.selectable_label(selected, label).clicked() && !selected {
                    *kind = default_kind_for(label);
                    res.changed = true;
                    res.rebake = true;
                }
            }
        });
    res
}

/// Full editor for one [`NodeKind`]: a kind-picker combo box plus the selected
/// variant's parameter widgets.
///
/// `id` scopes egui widget ids so multiple node editors can live in one `Ui`
/// (e.g. an inspector list, or the Phase-2 graph canvas) without colliding.
/// Picking a new kind from the dropdown replaces the node with that kind's
/// `Default`, which counts as both a change and a commit.
pub fn node_kind_editor(ui: &mut egui::Ui, kind: &mut NodeKind, id: egui::Id) -> EditorResponse {
    let mut res = EditorResponse::NONE;
    ui.push_id(id, |ui| {
        egui::ComboBox::from_label("Kind")
            .selected_text(node_kind_label(kind))
            .show_ui(ui, |ui| {
                for label in KIND_LABELS.iter().copied() {
                    let selected = node_kind_label(kind) == label;
                    if ui.selectable_label(selected, label).clicked() && !selected {
                        *kind = default_kind_for(label);
                        res.changed = true;
                        res.rebake = true;
                    }
                }
            });
        res.merge(node_kind_body(ui, kind));
    });
    res
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::ui::test_paint::shapes;

    /// Every string `body` paints for `kind`, on a headless context.
    fn painted_body(kind: &mut NodeKind) -> Vec<String> {
        let ctx = egui::Context::default();
        let input = egui::RawInput {
            screen_rect: Some(egui::Rect::from_min_size(
                egui::Pos2::ZERO,
                egui::vec2(600.0, 600.0),
            )),
            ..Default::default()
        };
        let out = ctx.run_ui(input, |ui| {
            egui::CentralPanel::default().show(ui, |ui| {
                node_kind_body(ui, kind);
            });
        });
        shapes(&out)
            .into_iter()
            .filter_map(|s| match s {
                egui::Shape::Text(t) => Some(t.galley.text().to_owned()),
                _ => None,
            })
            .collect()
    }

    /// B15 (#59, Overlands #1332): a Gate in a patch with no sequence
    /// behind it holds open for the whole bake, and an ADSR driven by one
    /// therefore never releases — a pluck authored in a Patch slot hums.
    /// The two bodies that depend on the gate window say so.
    #[test]
    fn the_gate_and_the_adsr_say_the_gate_is_always_open_in_a_standalone_patch() {
        for mut kind in [
            NodeKind::Gate(Gate::default()),
            NodeKind::Adsr(AdsrEnvelope::default()),
        ] {
            let name = node_kind_label(&kind);
            let painted = painted_body(&mut kind);
            assert!(
                painted
                    .iter()
                    .any(|t| t.contains("always open") && t.contains("standalone patch")),
                "{name}'s body does not say its gate is always open in a standalone \
                 patch; it paints {painted:?}"
            );
            assert!(
                painted.iter().any(|t| t.contains("notes")),
                "{name}'s body does not say a sequence's notes drive it: {painted:?}"
            );
        }
    }

    #[test]
    fn label_round_trips_through_default_kind() {
        // Every label maps to a kind whose label is itself — so the picker's
        // selected-text and the dropdown rows stay consistent.
        for label in KIND_LABELS.iter().copied() {
            let kind = default_kind_for(label);
            assert_eq!(
                node_kind_label(&kind),
                label,
                "round-trip failed for {label}"
            );
        }
    }

    #[test]
    fn unknown_label_falls_back_to_silence() {
        assert!(matches!(default_kind_for("nonsense"), NodeKind::Silence));
    }

    /// Every kind `symbios-audio` ships is offered by the picker, and the
    /// picker offers nothing else.
    ///
    /// The list this used to walk was hand-written here, so it could only
    /// ever agree with the hand-written `KIND_LABELS` beside it — both went
    /// stale together the moment a kind was added upstream, and neither test
    /// could notice. `NodeKind::defaults()` comes from the crate that
    /// defines the kinds, which is the only place the roster can be
    /// authoritative.
    #[test]
    fn the_picker_offers_exactly_the_kinds_upstream_ships() {
        let upstream = NodeKind::defaults();
        assert_eq!(
            KIND_LABELS.len(),
            upstream.len(),
            "picker and upstream roster disagree on how many kinds there are"
        );
        for kind in &upstream {
            assert!(
                KIND_LABELS.contains(&node_kind_label(kind)),
                "{} missing from KIND_LABELS",
                node_kind_label(kind)
            );
        }
        for label in KIND_LABELS.iter().copied() {
            assert!(
                upstream.iter().any(|k| node_kind_label(k) == label),
                "picker offers {label}, which upstream does not ship"
            );
        }
    }

    /// `Unknown` is a decode landing place, never an offer. Picking it would
    /// build a node this build cannot edit and cannot write back.
    #[test]
    fn the_picker_never_offers_unknown() {
        assert!(!KIND_LABELS.contains(&node_kind_label(&NodeKind::Unknown)));
        assert!(!KIND_LABELS.contains(&"Unknown"));
        // And the label for it is still the one the fallback text uses, so a
        // node box that meets one is titled rather than blank.
        assert_eq!(node_kind_label(&NodeKind::Unknown), "Unknown");
    }
}
